### ISSUE TITLE
Bevy version mismatch

### ISSUE THREAD

**Issue by acvogel** [guimcaballero/bevy_rhythm#4]
The [blog post](https://caballerocoll.com/blog/bevy-rhythm-game/) lists the Cargo.toml Bevy dependency as "0.4", but the [repository version](https://github.com/guimcaballero/bevy_rhythm/blob/fb4eb9125a99f16d0332310a808dfa9b1c64dead/Cargo.toml#L10) is "0.5". Folks trying to compile with "0.4" will get the following error, which I'm including for future searchers:

```
   Compiling bevy_input v0.4.0
error[E0599]: no function or associated item named `new_immediate` found for trait object `dyn Watcher` in the current scope
  --> /home/mbusux/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_asset-0.4.0/src/filesystem_watcher.rs:14:52
   |
14 |         let watcher: RecommendedWatcher = Watcher::new_immediate(move |res| {
   |                                                    ^^^^^^^^^^^^^ function or associated item not found in `dyn Watcher`

error[E0308]: mismatched types
  --> /home/mbusux/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_asset-0.4.0/src/filesystem_watcher.rs:24:28
   |
23 |     pub fn watch<P: AsRef<Path>>(&mut self, path: P) -> Result<()> {
   |                  - this type parameter
24 |         self.watcher.watch(path, RecursiveMode::Recursive)
   |                            ^^^^ expected `&Path`, found type parameter `P`
   |
   = note:   expected reference `&Path`
           found type parameter `P`

Some errors have detailed explanations: E0308, E0599.
For more information about an error, try `rustc --explain E0308`.
```
